name: flutterchallenges
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ^3.1.0
  flutter: ^3.13.0

dependencies:
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  scrollable_positioned_list: ^0.3.8
  go_router: ^10.1.2

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  go_router_builder: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/space_concept/
    - assets/travel_app/
    - assets/facebook_redesign/

  fonts:
    - family: Mark
      fonts:
        - asset: fonts/mark/Mark-Regular.otf
        - asset: fonts/mark/Mark-Bold.otf
          weight: 700
        - asset: fonts/mark/Mark-Medium.otf
          weight: 600
        - asset: fonts/mark/Mark-Light.otf
          weight: 500
        - asset: fonts/mark/Mark-Thin.otf
          weight: 400

    - family: SF-Pro-Display
      fonts:
        - asset: fonts/sf_pro_display/SF-Pro-Display-Regular.otf
        - asset: fonts/sf_pro_display/SF-Pro-Display-Bold.otf
          weight: 800
        - asset: fonts/sf_pro_display/SF-Pro-Display-Semibold.otf
          weight: 700
        - asset: fonts/sf_pro_display/SF-Pro-Display-Medium.otf
          weight: 600
        - asset: fonts/sf_pro_display/SF-Pro-Display-Light.otf
          weight: 500

    - family: SF-Pro-Text
      fonts:
        - asset: fonts/sf_pro_text/SF-Pro-Text-Regular.otf
        - asset: fonts/sf_pro_text/SF-Pro-Text-Bold.otf
          weight: 800
        - asset: fonts/sf_pro_text/SF-Pro-Text-Semibold.otf
          weight: 700
        - asset: fonts/sf_pro_text/SF-Pro-Text-Medium.otf
          weight: 600
        - asset: fonts/sf_pro_text/SF-Pro-Text-Light.otf
          weight: 500

    - family: Hybi11-Amigo
      fonts:
        - asset: fonts/hybi11_amigo/Hybi11-Amigo-Regular.ttf
        - asset: fonts/hybi11_amigo/Hybi11-Amigo-Bold.ttf
          weight: 800
        - asset: fonts/hybi11_amigo/Hybi11-Amigo-SemiBold.ttf
          weight: 700
        - asset: fonts/hybi11_amigo/Hybi11-Amigo-Light.ttf
          weight: 500

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    enabled: true
